"""init goals/habits/plan

Revision ID: 9e5dfda8a6f1
Revises: 
Create Date: 2025-08-11 06:01:52.739612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5dfda8a6f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('kpi', sa.String(length=255), nullable=True),
    sa.Column('fecha_objetivo', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('frecuencia', sa.String(length=1), nullable=True),
    sa.Column('hora_sugerida', sa.Time(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('plan_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_day_fecha'), 'plan_day', ['fecha'], unique=False)
    op.create_index(op.f('ix_plan_day_user_id'), 'plan_day', ['user_id'], unique=False)
    op.create_table('plan_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('dur_min', sa.Integer(), nullable=True),
    sa.Column('from_calendar', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_item_plan_id'), 'plan_item', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_item_plan_id'), table_name='plan_item')
    op.drop_table('plan_item')
    op.drop_index(op.f('ix_plan_day_user_id'), table_name='plan_day')
    op.drop_index(op.f('ix_plan_day_fecha'), table_name='plan_day')
    op.drop_table('plan_day')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
